### ISSUE TITLE
Integration spams pfSense with RADIUS requests

### ISSUE THREAD

**Issue by jackyaz** [travisghansen/hass-pfsense#71]
When using this integration with pfSense set to use RADIUS backend, and the integration is configured with a local user, the integration causes millions of authentication requests to the RADIUS server which as expected, fail, because its a local fallback user

Does the integration not cache the authentication state or is it creating a separate request for each sensor? On my system, the integration created 45 devices and 650 entities out of the box

**Comment by travisghansen** [comment]
Each scan interval it probably makes ~15 api calls to gather all the data using xmlrpc. Each request is authenticated anew as there is no session or something of that nature when using xmlrpc.

**Comment by jackyaz** [comment]
Any ideas why I'm seeing quite so many hits on NPS? Its definitely more than 15 calls every 30/60s

**Comment by travisghansen** [comment]
If you have device tracker turned on it's another few calls per interval for that...otherwise that doesn't make sense to me no.

It could be something internal to the xmlrpc server that's generating more traffic than desired. If possible it may be good to setup an xmlrpc client and just hit the service oneshot style and see how many hits you get for a single xmlrpc request.
